### ISSUE TITLE
What are you trying to do exactly?

### ISSUE THREAD

**Issue by 4sval** [Almesaody/FModel#15]
### Game

why

### Error

```shell
ctrl c
ctrl v
```

### Reproduction steps

I'm having a hard time understanding why this exists.
Why do you paste all my commits onto this cloned public repository?
Why do you create, answer, and close your own issues to replicate the official repo?
Why do you put so much time and effort into pasting everything?

I genuinely wanna know

**Comment by Almesaody** [comment]
Does this harm you in any way?

**Comment by Almesaody** [comment]
If the answer is no, then I enjoy it

**Comment by Almesaody** [comment]
and If the answer is yes, I will delete it
